services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: iron_q_up
      POSTGRES_PASSWORD: iron_q_down
      POSTGRES_DB: iron_queue
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U iron_q_up -d iron_queue"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
